# Generated by Django 2.1.4 on 2019-02-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_type', models.CharField(default='', max_length=100)),
                ('home_price', models.IntegerField(default='')),
                ('home_description', models.TextField(default='', max_length=1000)),
                ('home_location', models.CharField(default='', max_length=100)),
                ('home_contacts', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
