# Generated by Django 2.1.4 on 2019-02-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='home_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
